SUPABASE_URL = "https://zewmjurylmyjweyqotpw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpld21qdXJ5bG15andleXFvdHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MDAwOTYsImV4cCI6MjA3NDk3NjA5Nn0.4awJMuo5KHQM1-i0EaIZC0Gf8q9hQYwqRqZc10IWc2o"
